export const sample__foods = [
    {
        id: '1',
        name: 'Shrimp Siu Mai',
        cookTime: '15-20',
        price: 10,
        favorite: false,
        origins: ['northern china'],
        stars: 3.5,
        imageUrl: 'food-1.jpg',
        tags: ['DimSum', 'Appetizer', 'Seafood', 'All'],
    },
    {
        id: '2',
        name: 'Char Siu',
        cookTime: '15-20',
        price: 12,
        favorite: true,
        origins: ['guangdong china'],
        stars: 5,
        imageUrl: 'food-2.jpg',
        tags: ['Sweet', 'Appetizer', 'Meat', 'All'],
    },
    {
        id: '3',
        name: 'Scallion Pancake',
        cookTime: '5-10',
        price: 8,
        favorite: true,
        origins: ['shanghai china'],
        stars: 4,
        imageUrl: 'food-3.jpg',
        tags: ['Vegetarian', 'Appetizer', 'All'],
    },
    {
        id: '4',
        name: 'Yeung Chow Fried Rice',
        cookTime: '20-25',
        price: 14,
        favorite: false,
        origins: ['yangzhou china'],
        stars: 4.5,
        imageUrl: 'food-4.jpg',
        tags: ['Rice', 'Main-Dish', 'Seafood', 'All'],
    },
    {
        id: '5',
        name: 'Kung Pao Chicken',
        cookTime: '25-30',
        price: 16,
        favorite: true,
        origins: ['southern china'],
        stars: 3,
        imageUrl: 'food-5.jpg',
        tags: ['Spicy', 'Main-Dish', 'Meat', 'Rice', 'All'],
    },
    {
        id: '6',
        name: 'Mandarin Fish',
        cookTime: '25-30',
        price: 20,
        favorite: false,
        origins: ['suzhou china'],
        stars: 4.5,
        imageUrl: 'food-6.jpg',
        tags: ['Sweet', 'Main-Dish', 'Seafood', 'All'],
    },
];

export const sample__tags = [
    { name: 'All', count: 6 },
    { name: 'DimSum', count: 1 },
    { name: 'Appetizer', count: 3 },
    { name: 'Seafood', count: 3 },
    { name: 'Meat', count: 2 },
    { name: 'Sweet', count: 2 },
    { name: 'Vegetarian', count: 1 },
    { name: 'Rice', count: 2 },
    { name: 'Spicy', count: 1 },
    { name: 'Main-Dish', count: 3 },
]